// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBNzwW-85F547c3uBhOC-GQOgfQdRQ45U',
    appId: '1:743537463259:web:76209c51963490e52aa1fe',
    messagingSenderId: '743537463259',
    projectId: 'insula-81384',
    authDomain: 'insula-81384.firebaseapp.com',
    storageBucket: 'insula-81384.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRk0gtVyY-UuO3xl4jDNAaP7GrqrUxBvQ',
    appId: '1:743537463259:android:c00365d5c7c691fc2aa1fe',
    messagingSenderId: '743537463259',
    projectId: 'insula-81384',
    storageBucket: 'insula-81384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxm8CLNPRYL0graME4K5ibQUqb3V_JfyM',
    appId: '1:743537463259:ios:851dfe8bbce0fa492aa1fe',
    messagingSenderId: '743537463259',
    projectId: 'insula-81384',
    storageBucket: 'insula-81384.firebasestorage.app',
    iosBundleId: 'com.example.insula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxm8CLNPRYL0graME4K5ibQUqb3V_JfyM',
    appId: '1:743537463259:ios:851dfe8bbce0fa492aa1fe',
    messagingSenderId: '743537463259',
    projectId: 'insula-81384',
    storageBucket: 'insula-81384.firebasestorage.app',
    iosBundleId: 'com.example.insula',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBNzwW-85F547c3uBhOC-GQOgfQdRQ45U',
    appId: '1:743537463259:web:13be1003d9d0aba32aa1fe',
    messagingSenderId: '743537463259',
    projectId: 'insula-81384',
    authDomain: 'insula-81384.firebaseapp.com',
    storageBucket: 'insula-81384.firebasestorage.app',
  );
}
